FROM ubuntu   

# Create app directory

RUN apt-get update
RUN apt-get -qq update
RUN apt-get -y install curl
RUN apt-get -y install sudo
RUN apt-get -y install  gnupg
RUN apt-get install -y nodejs npm
RUN apt-get install --yes build-essential
RUN node --version
RUN npm --version

